Repository paketo-buildpacks/adoptium, pull requests merged in 2021-09, with the labels that each got.

#115 Renames project from AdoptOpenJDK to Adoptium
  .github/pipeline-descriptor.yml
  .github/workflows/create-package.yml
  .github/workflows/update-jdk-11.yml
  .github/workflows/update-jdk-16.yml
  .github/workflows/update-jdk-8.yml
  .github/workflows/update-jre-11.yml
  .github/workflows/update-jre-16.yml
  .github/workflows/update-jre-8.yml
  .github/workflows/update-jvmkill.yml
  NOTICE
  README.md
  buildpack.toml
  go.mod
  scripts/build.sh
Labels: type:task, semver:major

#117 Remove JVM Kill Agent and JRE 16 from CI
  .github/pipeline-descriptor.yml
Labels: type:bug, semver:patch

#120 Add Java 17
  .github/pipeline-descriptor.yml
  buildpack.toml
Labels: type:dependency-upgrade, semver:minor

#122 Bumped libjvm to 1.31.0
  README.md
  buildpack.toml
  go.sum
Labels: semver:patch, type:dependency-upgrade
